### ISSUE TITLE
Device T1012 not working

### ISSUE THREAD

**Issue by rtomasik** [sebmos/node-eufy-api#11]
From cli:

``
> node-eufy-api@0.3.1 cli:verbose /home/eufy/node-eufy-api
> node lib/cli.js --verbose

? Eufy account email XXX
? Eufy account password [hidden]
Logging in
Loading devices
(AbstractDevice.new) Create device (model: T1012, code: 476700EE1D5F48BA)
(AbstractDevice.new) Create device (model: T1012, code: F67F39B1E1A84DCE)
Logged in, devices loaded
? Save credentials locally for future use? Yes

? Choose device Nela (Model: T1012, Code: 476700EE1D5F48BA, IP Address: 192.168.5.239)
(AbstractDevice.connect) Connecting
(TcpSocket.connect) Connecting to 192.168.5.239
(AbstractDevice.new) TCP Socket connected
(AbstractDevice.connect) Connected to device Nela (Model: T1012, Code: 476700EE1D5F48BA, IP Address: 192.168.5.239)
(AbstractDevice.connect) Loading current device state
(LightBulb.loadCurrentState) Loading current device state
(LightBulb.getState) Loading current device state
(AbstractDevice.getSequence) Loading current sequence number
(AbstractDevice.sendPacketWithResponse) 08a8947e1210343736373030454531443546343842411a020800
(encryptPacket) Extended: 08a8947e1210343736373030454531443546343842411a020800000000000000
(encryptPacket) Encrypted: 60c9b13a7ff9d57191c9b51df1ed8a46384ec162e1eb90a0e6c2065e4ded849d
(AbstractDevice.sendPacket) Sending encrypted packet: 60c9b13a7ff9d57191c9b51df1ed8a46384ec162e1eb90a0e6c2065e4ded849d
(AbstractDevice.sendPacketWithResponse) Response received: 8094e62d35766f51601d08d33601c9ac
(AbstractDevice.sendPacketWithResponse) Response decrypted: 0b0008bd8a9c0312001a020801000000
(AbstractDevice.sendPacketWithResponse) Expected packet length: 11
(AbstractDevice.sendPacketWithResponse) Serialized packet: 08bd8a9c0312001a020801
(AbstractDevice.sendPacketWithResponse) Serialized packet length: 11
(AbstractDevice.sendPacketWithResponse) Deserializing response as T1012Packet
(AbstractDevice.sendPacketWithResponse) Decoded packet: {"sequence":6751549,"code":"","ping":{"type":1}}
(AbstractDevice.getSequence) Current sequence number: 6751549
(LightBulb.getState) Sending request to device
(AbstractDevice.sendPacketWithResponse) 08be8a9c03121034373637303045453144354634384241
(encryptPacket) Extended: 08be8a9c03121034373637303045453144354634384241000000000000000000
(encryptPacket) Encrypted: ad947e2a3d95376409378f720c068570c1e4751710b1a8e9d1713a796d0fe9ea
(AbstractDevice.sendPacket) Sending encrypted packet: ad947e2a3d95376409378f720c068570c1e4751710b1a8e9d1713a796d0fe9ea
Socket closed
(AbstractDevice.new) TCP Socket connected
Error connecting to device: Socket closed without sending response
``

Is there a chance to operate this light bulb?

**Comment by sebmos** [comment]
Hey @rtomasik - this is related to https://github.com/sebmos/node-eufy-api/issues/2, which is a problem on the light bulb. Eufy hasn't fixed that problem yet, and a workaround hasn't been found yet, either.

**Comment by rtomasik** [comment]
> Hey @rtomasik - this is related to #2, which is a problem on the light bulb. Eufy hasn't fixed that problem yet, and a workaround hasn't been found yet, either.

I just tested the python-lakeside version. And there everything works (connection, on / off).

**Comment by alexwgoody** [comment]
I'm having the same issue. the tunable bulb is not connecting.

I see your note on connection, on/off, but this is a tunable bulb, so it needs to ideally also control brightness and white level

**Comment by sebmos** [comment]
@alexwgoody & @rtomasik - I recently made a change that might fix the light bulb behaviour - it looks like there was a bug in addition to the one I've linked to. Would appreciate your feedback!

**Comment by mbellis18** [comment]
> @alexwgoody & @rtomasik - I recently made a change that might fix the light bulb behaviour - it looks like there was a bug in addition to the one I've linked to. Would appreciate your feedback!

This is the errors I'm seeing in the log of my HOOBS setup for the T1012 bulbs:
12/20/2020, 11:44:33 AM [eufy] Error loading power state on device: My Smart Bulb 1  -  Error: Socket closed without sending response
    at Timeout.<anonymous> (/home/hoobs/.hoobs/node_modules/node-eufy-api/lib/tcp-socket.js:153:48)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
12/20/2020, 11:44:33 AM [eufy] Error getting brightness on device: My Smart Bulb 1  -  Error: Socket closed without sending response
    at Timeout.<anonymous> (/home/hoobs/.hoobs/node_modules/node-eufy-api/lib/tcp-socket.js:153:48)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
12/20/2020, 11:44:33 AM [eufy] Error getting temperature on device: My Smart Bulb 1  -  Error: Socket closed without sending response
    at Timeout.<anonymous> (/home/hoobs/.hoobs/node_modules/node-eufy-api/lib/tcp-socket.js:153:48)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)

Let me know if there is anything I can do to help troubleshoot, I had to reset the bulbs as in my previous setup they would immediately get deleted on reboot.

**Comment by mbellis18** [comment]
> @alexwgoody & @rtomasik - I recently made a change that might fix the light bulb behaviour - it looks like there was a bug in addition to the one I've linked to. Would appreciate your feedback!

@sebmos 

This is the errors I'm seeing in the log of my HOOBS setup for the T1012 bulbs:
12/20/2020, 11:44:33 AM [eufy] Error loading power state on device: My Smart Bulb 1 - Error: Socket closed without sending response
at Timeout. (/home/hoobs/.hoobs/node_modules/node-eufy-api/lib/tcp-socket.js:153:48)
at listOnTimeout (internal/timers.js:554:17)
at processTimers (internal/timers.js:497:7)
12/20/2020, 11:44:33 AM [eufy] Error getting brightness on device: My Smart Bulb 1 - Error: Socket closed without sending response
at Timeout. (/home/hoobs/.hoobs/node_modules/node-eufy-api/lib/tcp-socket.js:153:48)
at listOnTimeout (internal/timers.js:554:17)
at processTimers (internal/timers.js:497:7)
12/20/2020, 11:44:33 AM [eufy] Error getting temperature on device: My Smart Bulb 1 - Error: Socket closed without sending response
at Timeout. (/home/hoobs/.hoobs/node_modules/node-eufy-api/lib/tcp-socket.js:153:48)
at listOnTimeout (internal/timers.js:554:17)
at processTimers (internal/timers.js:497:7)

Let me know if there is anything I can do to help troubleshoot, I had to reset the bulbs as in my previous setup they would immediately get deleted on reboot.

**Comment by sebmos** [comment]
Can you run the CLI in verbose mode & post the logs @mbellis18?

`npm run cli:verbose`

**Comment by mbellis18** [comment]
> Can you run the CLI in verbose mode & post the logs @mbellis18?
> 
> `npm run cli:verbose`

@sebmos 

Not an expert here, can I run this in the terminal of my hoobs setup?  Thanks!

**Comment by sebmos** [comment]
I'm not familiar with hoobs, so I can't help with those specifics. I would have suggested you simply check out this repo independently and run the command-line interface (README.md on this repo will help).
As a first trouble-shooting step though: Can you ensure you're on the latest version of the plugin? I'm not sure how the integration actually works, but you might have to specify the latest version somewhere.

**Comment by andym1117** [comment]
Evening, 

complete amateur here. Getting a 'No Response' for my Eufy lights in HomeKit with the following logs:

Socket Error: This socket has been ended by the other party
[16/02/2021, 20:27:10] [eufy] Error loading power state on device: Hall  -  Error: Socket closed without sending response
    at Timeout.<anonymous> (/usr/local/lib/node_modules/homebridge-eufy/node_modules/node-eufy-api/lib/tcp-socket.js:153:48)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
[16/02/2021, 20:27:10] [eufy] Error getting brightness on device: Office  -  Error: Socket closed without sending response
    at Timeout.<anonymous> (/usr/local/lib/node_modules/homebridge-eufy/node_modules/node-eufy-api/lib/tcp-socket.js:153:48)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
[16/02/2021, 20:27:10] [eufy] Error loading power state on device: Office  -  Error: Socket closed without sending response
    at Timeout.<anonymous> (/usr/local/lib/node_modules/homebridge-eufy/node_modules/node-eufy-api/lib/tcp-socket.js:153:48)


PLEASE HELP!! TiA
