### ISSUE TITLE
Eufy Plug Mini T1202

### ISSUE THREAD

**Issue by gonenutsbrb** [sebmos/node-eufy-api#5]
So I have four of the mini plugs and they were all working fine until recently.  Now it appears that only two of them work.  Here's homebridge's journal output when grep'ing eufy:

`Mar 07 22:41:06 homebridge homebridge[953]: [3/7/2019, 10:41:06 PM] Loaded plugin: homebridge-eufy
Mar 07 22:41:06 homebridge homebridge[953]: [3/7/2019, 10:41:06 PM] Registering platform 'homebridge-eufy.eufy'
Mar 07 22:41:06 homebridge homebridge[953]: [3/7/2019, 10:41:06 PM] [eufy] Initializing eufy platform...
Mar 07 22:41:06 homebridge homebridge[953]: [3/7/2019, 10:41:06 PM] [eufy] Eufy initializing
Mar 07 22:41:06 homebridge homebridge[953]: [3/7/2019, 10:41:06 PM] [eufy] Add Accessory: Left Living Room - F4B73C43CC4B4F83
Mar 07 22:41:06 homebridge homebridge[953]: [3/7/2019, 10:41:06 PM] [eufy] Add Accessory: Right Living Room - AD28DCF6020D4AE0
Mar 07 22:41:06 homebridge homebridge[953]: [3/7/2019, 10:41:06 PM] [eufy] Add Accessory: Person1's Bedroom Light - 328165890976443D
Mar 07 22:41:06 homebridge homebridge[953]: [3/7/2019, 10:41:06 PM] [eufy] Add Accessory: Person2's Bedroom Light - E6302EAAFB2C4273
Mar 07 22:41:06 homebridge homebridge[953]: [3/7/2019, 10:41:06 PM] [eufy] Error connecting to accessory: { AssertionError: Assertion failed
Mar 07 22:41:06 homebridge homebridge[953]:     at new goog.asserts.AssertionError (/usr/lib/node_modules/homebridge-eufy/node_modules/google-protobuf/google-protobuf.js:98:603)
Mar 07 22:41:06 homebridge homebridge[953]:     at Object.goog.asserts.doAssertFailure_ (/usr/lib/node_modules/homebridge-eufy/node_modules/google-protobuf/google-protobuf.js:99:126)
Mar 07 22:41:06 homebridge homebridge[953]:     at Object.goog.asserts.assert (/usr/lib/node_modules/homebridge-eufy/node_modules/google-protobuf/google-protobuf.js:99:385)
Mar 07 22:41:06 homebridge homebridge[953]:     at jspb.BinaryWriter.writeInt32 (/usr/lib/node_modules/homebridge-eufy/node_modules/google-protobuf/google-protobuf.js:330:264)
Mar 07 22:41:06 homebridge homebridge[953]:     at Function.proto.lakeside.T1201Packet.serializeBinaryToWriter (/usr/lib/node_modules/homebridge-eufy/node_modules/node-eufy-api/lib/lakeside_pb.js:4360:12)
Mar 07 22:41:06 homebridge homebridge[953]:     at proto.lakeside.T1201Packet.serializeBinary (/usr/lib/node_modules/homebridge-eufy/node_modules/node-eufy-api/lib/lakeside_pb.js:4344:30)
Mar 07 22:41:06 homebridge homebridge[953]:     at PowerPlugOrSwitch.<anonymous> (/usr/lib/node_modules/homebridge-eufy/node_modules/node-eufy-api/lib/device-base.js:221:77)
Mar 07 22:41:06 homebridge homebridge[953]:     at step (/usr/lib/node_modules/homebridge-eufy/node_modules/node-eufy-api/lib/device-base.js:32:23)
Mar 07 22:41:06 homebridge homebridge[953]:     at Object.next (/usr/lib/node_modules/homebridge-eufy/node_modules/node-eufy-api/lib/device-base.js:13:53)
Mar 07 22:41:06 homebridge homebridge[953]:     at /usr/lib/node_modules/homebridge-eufy/node_modules/node-eufy-api/lib/device-base.js:7:71
Mar 07 22:41:06 homebridge homebridge[953]:     at __awaiter (/usr/lib/node_modules/homebridge-eufy/node_modules/node-eufy-api/lib/device-base.js:3:12)
Mar 07 22:41:06 homebridge homebridge[953]:     at PowerPlugOrSwitch.AbstractDevice.sendPacketWithResponse (/usr/lib/node_modules/homebridge-eufy/node_modules/node-eufy-api/lib/device-base.js:215:16)
Mar 07 22:41:06 homebridge homebridge[953]:     at PowerPlugOrSwitch.<anonymous> (/usr/lib/node_modules/homebridge-eufy/node_modules/node-eufy-api/lib/device-power-plug-or-switch.js:75:51)
Mar 07 22:41:06 homebridge homebridge[953]:     at step (/usr/lib/node_modules/homebridge-eufy/node_modules/node-eufy-api/lib/device-power-plug-or-switch.js:45:23)
Mar 07 22:41:06 homebridge homebridge[953]:     at Object.next (/usr/lib/node_modules/homebridge-eufy/node_modules/node-eufy-api/lib/device-power-plug-or-switch.js:26:53)
Mar 07 22:41:06 homebridge homebridge[953]:     at fulfilled (/usr/lib/node_modules/homebridge-eufy/node_modules/node-eufy-api/lib/device-power-plug-or-switch.js:17:58)
Mar 07 22:41:06 homebridge homebridge[953]: [3/7/2019, 10:41:06 PM] [eufy] Removing accessory: Left Living Room
Mar 07 22:41:06 homebridge homebridge[953]: [3/7/2019, 10:41:06 PM] [eufy] Error connecting to accessory: { AssertionError: Assertion failed
Mar 07 22:41:06 homebridge homebridge[953]:     at new goog.asserts.AssertionError (/usr/lib/node_modules/homebridge-eufy/node_modules/google-protobuf/google-protobuf.js:98:603)
Mar 07 22:41:06 homebridge homebridge[953]:     at Object.goog.asserts.doAssertFailure_ (/usr/lib/node_modules/homebridge-eufy/node_modules/google-protobuf/google-protobuf.js:99:126)
Mar 07 22:41:06 homebridge homebridge[953]:     at Object.goog.asserts.assert (/usr/lib/node_modules/homebridge-eufy/node_modules/google-protobuf/google-protobuf.js:99:385)
Mar 07 22:41:06 homebridge homebridge[953]:     at jspb.BinaryWriter.writeInt32 (/usr/lib/node_modules/homebridge-eufy/node_modules/google-protobuf/google-protobuf.js:330:264)
Mar 07 22:41:06 homebridge homebridge[953]:     at Function.proto.lakeside.T1201Packet.serializeBinaryToWriter (/usr/lib/node_modules/homebridge-eufy/node_modules/node-eufy-api/lib/lakeside_pb.js:4360:12)
Mar 07 22:41:06 homebridge homebridge[953]:     at proto.lakeside.T1201Packet.serializeBinary (/usr/lib/node_modules/homebridge-eufy/node_modules/node-eufy-api/lib/lakeside_pb.js:4344:30)
Mar 07 22:41:06 homebridge homebridge[953]:     at PowerPlugOrSwitch.<anonymous> (/usr/lib/node_modules/homebridge-eufy/node_modules/node-eufy-api/lib/device-base.js:221:77)
Mar 07 22:41:06 homebridge homebridge[953]:     at step (/usr/lib/node_modules/homebridge-eufy/node_modules/node-eufy-api/lib/device-base.js:32:23)
Mar 07 22:41:06 homebridge homebridge[953]:     at Object.next (/usr/lib/node_modules/homebridge-eufy/node_modules/node-eufy-api/lib/device-base.js:13:53)
Mar 07 22:41:06 homebridge homebridge[953]:     at /usr/lib/node_modules/homebridge-eufy/node_modules/node-eufy-api/lib/device-base.js:7:71
Mar 07 22:41:06 homebridge homebridge[953]:     at __awaiter (/usr/lib/node_modules/homebridge-eufy/node_modules/node-eufy-api/lib/device-base.js:3:12)
Mar 07 22:41:06 homebridge homebridge[953]:     at PowerPlugOrSwitch.AbstractDevice.sendPacketWithResponse (/usr/lib/node_modules/homebridge-eufy/node_modules/node-eufy-api/lib/device-base.js:215:16)
Mar 07 22:41:06 homebridge homebridge[953]:     at PowerPlugOrSwitch.<anonymous> (/usr/lib/node_modules/homebridge-eufy/node_modules/node-eufy-api/lib/device-power-plug-or-switch.js:75:51)
Mar 07 22:41:06 homebridge homebridge[953]:     at step (/usr/lib/node_modules/homebridge-eufy/node_modules/node-eufy-api/lib/device-power-plug-or-switch.js:45:23)
Mar 07 22:41:06 homebridge homebridge[953]:     at Object.next (/usr/lib/node_modules/homebridge-eufy/node_modules/node-eufy-api/lib/device-power-plug-or-switch.js:26:53)
Mar 07 22:41:06 homebridge homebridge[953]:     at fulfilled (/usr/lib/node_modules/homebridge-eufy/node_modules/node-eufy-api/lib/device-power-plug-or-switch.js:17:58)
Mar 07 22:41:06 homebridge homebridge[953]: [3/7/2019, 10:41:06 PM] [eufy] Removing accessory: Right Living Room`

Hope that helps, let me know if you need any more information or output.  I'm pretty new to homebridge and node in general, but happy to help out where I can!

Thank you for the hard work!

**Comment by sebmos** [comment]
Hey @gonenutsbrb,

Your problem seems to be the same as https://github.com/sebmos/node-eufy-api/issues/2 and 
https://github.com/google/python-lakeside/issues/11 in the original Python library. Unfortunately, neither of us have come up with a solution to this problem.

It appears to be due to a bug on the Eufy device.

**Comment by mrehler** [comment]
Out of my two smart plugs, one of mine is working, the other is not. The one that is not working works fine through the eufyHome app. 

[2019-03-21 homebridge error log.txt](https://github.com/sebmos/node-eufy-api/files/2994596/2019-03-21.homebridge.error.log.txt)

**Comment by sebmos** [comment]
Hey @heyhler,

It sounds like your problem is related to the one linked above.

As for the error log you attached - it doesn't appear to be related to the `node-eufy-api` package - at least the stack trace doesn't reference it. If there's a longer stack trace, please attach the full version of it.

**Comment by mrehler** [comment]
@sebmos those were the errors dumped to the console. Is there a different/more verbose error log that might have more details? In a separate file?
