### ISSUE TITLE
Socket closed without sending response (timeout.js:153)

### ISSUE THREAD

**Issue by digitalec** [sebmos/node-eufy-api#6]
I'm having an issue similar to #2 and #5 but this doesn't appear to be related to the sequence number but rather a timeout issue (see the homebridge output at the bottom).

I have removed one of the bulbs (T1011) from my account, readded and upgraded the firmware but no dice. Both bulbs are presently on the latest firmware available.

```
$ npm run cli:verbose

? Choose device Kitchen Lamp (Model: T1011, Code: 056E67FCDC6D4B5C, IP Address: 10.10.25.133)
(AbstractDevice.connect) Connecting
(TcpSocket.connect) Connecting to 10.10.25.133
(AbstractDevice.new) TCP Socket connected
(AbstractDevice.connect) Connected to device Kitchen Lamp (Model: T1011, Code: 056E67FCDC6D4B5C, IP Address: 10.10.25.133)
(AbstractDevice.connect) Loading current device state
(LightBulb.loadCurrentState) Loading current device state
(LightBulb.getState) Loading current device state
(AbstractDevice.getSequence) Loading current sequence number
(AbstractDevice.sendPacketWithResponse) 08f7f3111210303536453637464344433644344235431a020800
(encryptPacket) Extended: 08f7f3111210303536453637464344433644344235431a020800000000000000
(encryptPacket) Encrypted: eddc55378b6f3bdfe672fe6ab409ec1325b501e601105ebf3db3d06b9d4cf3e8
(AbstractDevice.sendPacket) Sending encrypted packet: eddc55378b6f3bdfe672fe6ab409ec1325b501e601105ebf3db3d06b9d4cf3e8
(AbstractDevice.sendPacketWithResponse) Response received: e42402a05d23d5ac60085a11286c973a
(AbstractDevice.sendPacketWithResponse) Response decrypted: 0c0008b190fde00212001a0208010000
(AbstractDevice.sendPacketWithResponse) Expected packet length: 12
(AbstractDevice.sendPacketWithResponse) Serialized packet: 08b190fde00212001a020801
(AbstractDevice.sendPacketWithResponse) Serialized packet length: 12
(AbstractDevice.sendPacketWithResponse) Deserializing response as T1012Packet
(AbstractDevice.sendPacketWithResponse) Decoded packet: {"sequence":740247601,"code":"","ping":{"type":1}}
(AbstractDevice.getSequence) Current sequence number: 740247601
(LightBulb.getState) Sending request to device
(AbstractDevice.sendPacketWithResponse) 08b290fde002121030353645363746434443364434423543
(encryptPacket) Extended: 08b290fde0021210303536453637464344433644344235430000000000000000
(encryptPacket) Encrypted: 4d5da1acb4bacd6ed95036f005d8dfcc375e7b443e80bff62096624c2aab95cd
(AbstractDevice.sendPacket) Sending encrypted packet: 4d5da1acb4bacd6ed95036f005d8dfcc375e7b443e80bff62096624c2aab95cd
Socket closed
(AbstractDevice.new) TCP Socket connected
Error connecting to device: Socket closed without sending response
```

```
$ homebridge

Logged in, devices loaded
[6/15/2019, 12:12:19 PM] [Eufy] Add Accessory: Kitchen Lamp - 056E67FCDC6D4B5C
[6/15/2019, 12:12:19 PM] [Eufy] Add Accessory: Living Room Lamp - 9AB6CF30D3A540A7
[6/15/2019, 12:12:20 PM] [Eufy] Error connecting to accessory: Error: Socket closed without sending response
    at Timeout.<anonymous> (/usr/local/lib/node_modules/homebridge-eufy/node_modules/node-eufy-api/lib/tcp-socket.js:153:48)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
[6/15/2019, 12:12:20 PM] [Eufy] Removing accessory: Kitchen Lamp
[6/15/2019, 12:12:20 PM] [Eufy] Error connecting to accessory: Error: Socket closed without sending response
    at Timeout.<anonymous> (/usr/local/lib/node_modules/homebridge-eufy/node_modules/node-eufy-api/lib/tcp-socket.js:153:48)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
[6/15/2019, 12:12:20 PM] [Eufy] Removing accessory: Living Room Lamp
```

**Comment by digitalec** [comment]
Sorry, found info at sebmos/homebridge-eufy#4; this is infact related to #2
